#!/usr/bin/env bash
# Setup HAProxy with SSL termination for subdomain www.lebenebotanicals.tech

# Install HAProxy and Certbot (Assuming you are on a Debian/Ubuntu system)
sudo apt-get update
sudo apt-get install -y haproxy certbot

# Create a certificate using Certbot
sudo certbot certonly --standalone -d www.lebenebotanicals.tech

# Create HAProxy configuration file
cat <<EOF > /etc/haproxy/haproxy.cfg
# Global Configuration
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

# Defaults Configuration
defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

# Frontend Configurations
frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/www.lebenebotanicals.tech/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend www-backend

# Backend Configuration
backend www-backend
   server 235164-web-01 18.204.20.244:80 check
   server  235164-web-02 100.25.159.16:80 check

EOF

# Restart HAProxy to apply the configuration
sudo service haproxy restart

# Test the setup by querying the subdomain
curl -sI https://www.lebenebotanicals.tech
curl https://www.lebenebotanicals.tech
