#!/usr/bin/env bash
# Update and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create custom HTTP response header file
echo 'add_header X-Served-By $hostname;' | sudo tee /etc/nginx/conf.d/custom_response_header.conf

# Remove the default symbolic link in sites-enabled
sudo rm -f /etc/nginx/sites-enabled/default

# Reload Nginx to apply changes
sudo systemctl reload nginx

# Ensure Nginx and custom header are configured correctly
if [ "$(curl -sI localhost | grep -i 'X-Served-By' | awk '{print $2}')" == "03-web-01" ] && \
   [ "$(curl -sI localhost | grep -i 'X-Served-By' | awk '{print $2}')" == "03-web-02" ]; then
    echo "Custom headers are configured correctly on both web-01 and web-02"
else
    echo "Custom headers are not configured correctly"
fi
