#!/usr/bin/env bash

# Update and install HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAproxy
echo "
frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 18.204.20.244:80 check
    server web-02 100.25.159.16:80 check" | sudo tee /etc/haproxy/haproxy.cfg

# Restart HAproxy to apply changes
sudo systemctl restart haproxy

# Ensure HAproxy is configured correctly
if [ "$(curl -sI 100.25.188.160 | grep -i 'X-Served-By' | awk '{print $2}')" == "03-web-01" ] && \
   [ "$(curl -sI 100.25.188.160 | grep -i 'X-Served-By' | awk '{print $2}')" == "03-web-02" ]; then
    echo "HAproxy is configured correctly"
else
    echo "HAproxy is not configured correctly"
fi
