#!/usr/bin/env bash
# Is the Host on the Network?
# Ping an IP address passed as an argument.

if [ $# -ne 1 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

ip_address="$1"

# Ping the IP address 5 times and display the results
ping -c 5 "$ip_address"

