#!/usr/bin/env bash
# This script displays messages based on loop iteration

# Initialize counter
count=1

# loop from 1 to 10 using while loop
while [ $count -le 10 ]; do
    # Check for specific loop iterations and display appropriate messages
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi

    ((count++))
done

