#!/usr/bin/env bash
# This script displays numbers from 1 to 20
# Displays specific messages for 4, 9 and 17

# Initialize counter
count=1

# Use a while loop to loop from 1 to 20
while [ $count -le 20 ]; do
    case $count in
        4)
            echo "$count"
            echo "bad luck from China"
            ;;
        9)
            echo "$count"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$count"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$count"
            ;;
    esac

    ((count++))
done

