#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except
# the following TCP ports:22 (SSH),443 (HTTPS SSL),80 (HTTP)

# Update the package repository and install UFW
sudo apt-get update
sudo apt-get install ufw

# Set the default incoming policy to deny
sudo ufw default deny incoming

# Allow SSH (port 22)
sudo ufw allow 22/tcp

# Allow HTTPS (port 443)
sudo ufw allow 443/tcp

# Allow HTTP (port 80)
sudo ufw allow 80/tcp

# Enable the UFW firewall
sudo ufw enable

# Display the UFW status to confirm the rules
sudo ufw status
