#!/usr/bin/env bash
# Configures the localhost and facebook.com resolutions.

cp /etc/hosts ~/hosts.new
# make a backup copy of the original /etc/hosts file and
# save it as ~/hosts.new in the user's home directory.

echo "127.0.0.2		localhost" > ~/hosts.new
# create a new file ~/hosts.new (or overwrite it if it already exists)
# add the line "127.0.0.2    localhost" to it.
# configure the resolution of "localhost" to point to the IP address 127.0.0.2.

echo "8.8.8.8		facebook.com" >> ~/hosts.new
# append line ("8.8.8.8    facebook.com") to the ~/hosts.new file. 
# configure the resolution of "facebook.com" to point to the IP address 8.8.8.8.

cp -f ~/hosts.new /etc/hosts
# replace the original /etc/hosts file with the modified ~/hosts.new file.
# The -f flag force copies, overriding the original /etc/hosts file if it exists.
