#!/usr/bin/env bash
# This script fixes Apache to serve a "Hello Holberton" page in a Docker container
# Run Apache on the holbertonschool/265-0 Docker container.
echo "ServerName localhost" >> /etc/apache2.conf
service apache2 start
