#!/usr/bin/env bash
# Configures Nginx to run as the nginx user and listen on port 8080
sed -i 's/user root/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
